# Generated by Django 5.0 on 2024-01-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="fecha_inscrip",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="telefono",
            field=models.IntegerField(null=True),
        ),
    ]
